### ISSUE TITLE
Colors

### ISSUE THREAD

**Issue by apas** [michaeldfallen/git-prompt#12]
A better color palette (or a collection of) to support existing terminal color themes would be very much appreciated.

![](https://photos-6.dropbox.com/t/2/AAA-yehqWCUZHMEvaiaj90CqtuLwaVyFi6tnBEKDaZR3uA/12/353609/png/32x32/1/1440604800/0/2/Screenshot%202015-08-26%2009.59.40.png/CMnKFSABIAIgAyAEIAUgBiAHKAEoAigDKAc/8rmiYgHTDU-WlMwpMwIFzfyJFNeb5jL66mnUrL1Ce_M?size=1024x768&size_mode=2)

**Comment by jackmaney** [comment]
:+1: I'm using a solarized dark color scheme, and I can only see the portion of my `git-radar` prompt that's within the parentheses.

**Comment by michaeldfallen** [comment]
I use the built in colours that are set by your terminal, so in theory it's due to your terminal having the same colour set for the background as the black colour. 

hmm, I should probably change the `git:(` part to something other than the "bold black" colour and the branch name to reset instead of "bold white" (which in my molokai colour scheme is light grey.

**Comment by michaeldfallen** [comment]
Am I right in assuming you use: https://github.com/tomislav/osx-terminal.app-colors-solarized? I just installed it and found that it's put the darker colours (content tones, dark black, etc) in to the "bright" colour slots. I'll try to do up some colour changes that support it but most have the colours become lighter in the "bright" slots so it might not marry up quite right.

**Comment by apas** [comment]
@michaeldfallen yes, I use Solarized Dark from the official iTerm package.

**Comment by jackmaney** [comment]
@michaeldfallen Actually, I'm using https://github.com/altercation/solarized/tree/master/iterm2-colors-solarized It's unclear if there's a difference (other than one of them appearing to use base 64 encoding (I think?) to encode colors vs specifying RGB).

**Comment by michaeldfallen** [comment]
I'll add an alternative color scheme controlled by args. Might take a while to get it looking nice though.

**Comment by jackmaney** [comment]
Would it be easier to have configurable colors via, say, `~/.git-radarrc` (or similar)? Then you could specify semantic colors, eg:

```
export GIT_RADAR_BRANCH_NAME_COLOR="\[033[36m\]" # cyan
export GIT_RADAR_UNTRACKED_COLOR="\e[97m" #white
# etc
```

**Comment by jedsmith** [comment]
+1 on configurable colors, particularly for folks who are various types of color blind.

**Comment by michaeldfallen** [comment]
@jedsmith the colours are your terminals colours. So if you are colour blind it should pick up the colours you've chosen for your terminal, which I would assume are colourblind safe? Are there terminal themes that are colourblind safe? http://ciembor.github.io/4bit/ is quite useful for creating a theme so could help.

**Comment by michaeldfallen** [comment]
@jackmaney yeah you're right, having each part that can be coloured as a configurable value, either through args / env / rc file is probably the best way to go :+1:

**Comment by Droogans** [comment]
You're using green and red for staged/unstaged changes, which isn't colorblind friendly at all. I've defined these colors in my `.gitconfig` to be cyan and red, respectively. Is there a reason you're not pulling these preferences from a user's `.gitconfig`?

**Comment by michaeldfallen** [comment]
@Droogans No, I'm using the colour that your terminal claims is `green`. If you're colourblind you need to redefine the colours you can't see to something else that you can see. It'll still be considered `green` and git-radar will still use it, but you'll be able to see it. 

So while you have set those colours in `.gitconfig` you need to set them in your terminal so that any process that asks for `green` will get the colour you can see.

**Comment by michaeldfallen** [comment]
I believe that #39 has solved this for you.
