### ISSUE TITLE
Remove the space before the output

### ISSUE THREAD

**Issue by eproxus** [michaeldfallen/git-prompt#15]
This is a request to remove the space prefix of the output of `git-radar`. This would give more flexibility to theme builders over where the output can be placed. It would also be more consistent, because there's no padding at the end of the output.

**Comment by michaeldfallen** [comment]
Fair point. I had added the space since bash can't collapse spaces. So in these examples you would get:

```
#in a repo
> /repo-name git:(master) $

#out side of repo
> /repo-name  $
```

I.e. two spaces, since they don't collapse. The solution was to output a space before the git-radar as part of git-radars output, that way there would be only one space. I made these spaces configurable in the different parts ([remote commits][separator][branch][separator][localcommits][separator][staged files]etc) but didn't think to change the initial space.

Another request has been made to make the `git:(` parts configurable. Currently I have `git:(` as a prefix, so if I make that configurable (with a sane default) would that satisfy what you're looking for?

**Comment by eproxus** [comment]
Ah, good point. Hadn't thought about that.

In my current theme, I have a check for VCS and then run `git-radar` or my SVN equivalent only if there is a repo in the first place.

In that case either a `--no-space` flag would be nice or actually making the whole prefix string configurable as well. I guess that's even better.

**Comment by michaeldfallen** [comment]
As #40 will cover this issue by providing the ability to configure the entire shape of the prompt. closing for now.
