### ISSUE TITLE
Duplicate branches pointing to same upstream

### ISSUE THREAD

**Issue by michaeldfallen** [michaeldfallen/git-prompt#2]
When you have two branches point to the same upstream branch you get the following message:

```
fatal: ambiguous argument 'origin/branch                                                                                               
origin/branch...HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
fatal: ambiguous argument 'origin/branch
origin/branch...HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

due to the `remote_branch_name` function having trouble finding which branch to follow

**Comment by asaaki** [comment]
This also happens if you have some branch setup like following:

```
master
something/master
```

When working on `master` branch it also returns more than a single line.

My workaround in my case is:

``` shell
# in radar-base.sh -> remote_branch_name()
local remoteBranch="$(git for-each-ref --format='%(upstream:short)' refs/heads $localRef 2>/dev/null | grep origin/$localRef)"
```

So, basically in the grep command prefix with `origin/` is added.

_(Unfortunately this breaks the nice branch diff output and stays on `upstream ⚡ <branch>`.)_

In general, if you have two or more branches sharing identical suffixes, git-radar will fail for the branch without the prefix.
