### ISSUE TITLE
feature req: color prompt red when folder not writable

### ISSUE THREAD

**Issue by orefalo** [michaeldfallen/git-prompt#95]
feature req: color prompt red when folder not writable

My 2c. ;-0

**Comment by michaeldfallen** [comment]
That's a nice idea (and something I might add in to my own prompt config) but it's not particularly git related. Plus I would have thought colouring the folder name red would be more specific, since its the folder that can't be written. Maybe render the UTF8 lock symbol beside the folder name as well. Ok, I like this idea quite a bit.

But... it's not git related. This plugin is all about providing at a glance info about a git repo. For that reason I won't be adding it to git-radar. Though I will add it to my dotfiles (I'll paste a link here once implemented).

Closing.
