### ISSUE TITLE
cd .git/ produces fatal: /usr/lib/git-core/git-stash cannot be used without a working tree

### ISSUE THREAD

**Issue by oryband** [michaeldfallen/git-prompt#98]
``` bash
$ cd ~/.git-radar/.git  # for example using the git-radar repo dir
fatal: /usr/lib/git-core/git-stash cannot be used without a working tree.
$ # i press enter
fatal: /usr/lib/git-core/git-stash cannot be used without a working tree.
```

this happens on every command i execute. spams the terminal.

**Comment by hallzy** [comment]
hm weird... I tracked down the problem to be commit 989911c595b19aac9ecb4aa87eb2ac4d57610c86. This is the first commit in the history to have this issue.

The problem would seem to be because the command that checks for stashes still executes within the .git directory. That is the error you see if you try to do a "git stash list" yourself.

**Comment by hallzy** [comment]
I have a fix for this in PR #99. All it does is check if the current directory is called ".git".

If the owner would prefer a different way of checking, that is fine too, but I thought I would go ahead and submit this.

**Comment by oryband** [comment]
this might have caused #100

**Comment by michaeldfallen** [comment]
Closing as fixed

**Comment by rholmboe** [comment]
Would like to re-open this one, since going down a step further down in .git directory yells the same error. Also opened PR #107 to fix the issue.
